# Generated by Django 6.0.2 on 2026-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_madical_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
