# Generated by Django 6.0.2 on 2026-09-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0003_medical_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madical_order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('faild', 'Faild'), ('cancle', 'Cancle')], max_length=100),
        ),
    ]
