# Generated by Django 6.0.2 on 2026-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0004_alter_madical_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='madical_order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='madical_order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='madical_order',
            name='razorpay_signeture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
